// pages/competitors.tsx
import { apiPost, apiGet } from '../lib/api'
import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import DashboardLayout from '../components/layout/DashboardLayout'
import { withAuth } from '../lib/withAuth'
import { usePlatform, PLATFORMS } from '../contexts/PlatformContext'
import { AIBadge, Spinner, EmptyState } from '../components/ui'
import toast from 'react-hot-toast'
import { useAuth } from '../contexts/AuthContext'
import { saveCompetitor, getCompetitors, deleteCompetitor } from '../services/firestore'
import { FiPlus, FiTrash2, FiRefreshCw, FiSearch, FiCopy, FiDownload, FiX, FiExternalLink, FiZap } from 'react-icons/fi'

function CompetitorsPage() {
  const { activePlatform } = usePlatform()
  const { user } = useAuth()
  const activePlt = PLATFORMS.find(p => p.code === activePlatform)!

  const [savedCompetitors, setSavedCompetitors] = useState<any[]>([])
  const [newName, setNewName] = useState('')
  const [niche, setNiche] = useState('')
  const [analysis, setAnalysis] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [analyzing, setAnalyzing] = useState('')
  const [cloning, setCloning] = useState(false)
  const [blueprint, setBlueprint] = useState<any>(null)
  const [videoSeo, setVideoSeo] = useState<any>(null)
  const [seoLoading, setSeoLoading] = useState('')

  const cloneChannel = async () => {
    if (!analysis?.name) return
    setCloning(true)
    setBlueprint(null)
    try {
      const res = await apiPost('/api/competitors/clone', {
        channelName: analysis.name, niche: analysis.niche || niche || 'general',
      })
      setBlueprint(res.data)
    } catch (e: any) {
      toast.error(e?.response?.data?.error || 'Clone failed. Try again.')
    } finally {
      setCloning(false)
    }
  }

  const analyzeVideo = async (videoId: string) => {
    setSeoLoading(videoId)
    setVideoSeo(null)
    try {
      const res = await apiPost('/api/videos/analyze', { videoId })
      setVideoSeo(res.data)
    } catch (e: any) {
      toast.error(e?.response?.data?.error || 'Video analysis failed')
    } finally {
      setSeoLoading('')
    }
  }

  const downloadBlueprintPDF = () => {
    if (!blueprint) return
    const w = window.open('', '_blank')
    if (!w) { toast.error('Allow popups to download'); return }
    w.document.write(`<!DOCTYPE html><html><head><title>Channel Blueprint — SRankIQ</title>
      <style>
        body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#111;max-width:720px;margin:40px auto;padding:0 24px;line-height:1.55}
        h1{font-size:26px;margin-bottom:2px} .sub{color:#666;font-size:13px;margin-bottom:28px}
        h2{font-size:15px;text-transform:uppercase;letter-spacing:1px;color:#0891b2;margin:26px 0 8px;border-bottom:1px solid #eee;padding-bottom:4px}
        ol{padding-left:20px} li{margin-bottom:6px} .box{background:#f6f8fa;border-radius:8px;padding:14px;font-size:14px}
        .foot{margin-top:40px;font-size:11px;color:#999;text-align:center}
      </style></head><body>
      <h1>Channel Launch Blueprint</h1>
      <div class="sub">Inspired by ${blueprint.sourceChannel} · Generated by SRankIQ · srankiq.com</div>
      <h2>Suggested Channel Names</h2>
      <ol>${(blueprint.suggestedNames || []).map((n: string) => `<li><b>${n}</b></li>`).join('')}</ol>
      <h2>Channel Description</h2><div class="box">${blueprint.channelDescription || ''}</div>
      ${blueprint.tagline ? `<h2>Tagline</h2><div class="box">${blueprint.tagline}</div>` : ''}
      <h2>10 Launch Video Titles</h2>
      <ol>${(blueprint.titles || []).map((t: string) => `<li>${t}</li>`).join('')}</ol>
      ${blueprint.contentPillars?.length ? `<h2>Content Pillars</h2><ol>${blueprint.contentPillars.map((p: string) => `<li>${p}</li>`).join('')}</ol>` : ''}
      ${blueprint.firstWeekPlan ? `<h2>First Week Plan</h2><div class="box">${blueprint.firstWeekPlan}</div>` : ''}
      <div class="foot">© SRankIQ — Social Media Ranking Intelligence</div>
      <script>window.onload = () => setTimeout(() => window.print(), 400)</script>
      </body></html>`)
    w.document.close()
  }

  useEffect(() => {
    if (user) loadSaved()
  }, [user])

  const loadSaved = async () => {
    if (!user) return
    const data = await getCompetitors(user.uid)
    setSavedCompetitors(data)
  }

  const analyze = async (name: string, save = true) => {
    setAnalyzing(name)
    setLoading(true)
    setAnalysis(null)
    try {
      const res = await apiPost('/api/competitors/analyze', {
        channelName: name,
        platform: activePlt.name,
        niche: niche || 'general',
      })
      setAnalysis(res.data)
      if (save && user) {
        await saveCompetitor(user.uid, { name, platform: activePlt.name, data: res.data })
        await loadSaved()
        toast.success(`${name} added to competitors`)
      }
    } catch (err: any) {
      toast.error('Analysis failed. Try again.')
    } finally {
      setLoading(false)
      setAnalyzing('')
    }
  }

  const remove = async (id: string) => {
    if (!user) return
    await deleteCompetitor(user.uid, id)
    await loadSaved()
    toast.success('Competitor removed')
  }

  return (
    <DashboardLayout title="Competitors">
      <div className="p-6 space-y-6">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-xl font-bold">👥 Competitor Intelligence</h1>
            <p className="text-muted text-sm">AI-powered competitor analysis for {activePlt.name}</p>
          </div>
          <AIBadge />
        </div>

        {/* Add competitor */}
        <div className="card">
          <h3 className="font-bold text-white mb-4">Analyze a Competitor</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-3">
            <div className="md:col-span-2">
              <label className="label">Channel / Account Name</label>
              <div className="relative">
                <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" size={14} />
                <input className="inp pl-9" value={newName} onChange={e => setNewName(e.target.value)}
                  placeholder="e.g. MrBeast, MKBHD, Gary Vee..." />
              </div>
            </div>
            <div>
              <label className="label">Niche (optional)</label>
              <input className="inp" value={niche} onChange={e => setNiche(e.target.value)}
                placeholder="e.g. tech, finance, fitness" />
            </div>
          </div>
          <button onClick={() => { if (newName) { analyze(newName); setNewName('') } else toast.error('Enter a name') }}
            disabled={loading}
            className="btn btn-cyan gap-2">
            {loading ? <Spinner size={15} /> : <FiPlus size={15} />}
            {loading ? 'Analyzing...' : 'Analyze Competitor'}
          </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Saved list */}
          <div className="card">
            <h3 className="font-bold text-white mb-4">Saved Competitors ({savedCompetitors.length})</h3>
            {savedCompetitors.length === 0 ? (
              <p className="text-muted text-sm text-center py-8">No competitors saved yet</p>
            ) : (
              <div className="space-y-2">
                {savedCompetitors.map((c: any) => (
                  <div key={c.id} className="flex items-center gap-3 p-3 bg-surf2 rounded-xl
                                            border border-white/5 hover:border-white/10 transition-colors">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-cyan/20 to-magenta/20
                                  flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
                      {c.name?.charAt(0)}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-semibold text-white truncate">{c.name}</div>
                      <div className="text-xs text-muted">{c.platform}</div>
                    </div>
                    <div className="flex gap-1">
                      <button onClick={() => analyze(c.name, false)}
                        className="w-7 h-7 rounded-lg hover:bg-white/10 flex items-center justify-center text-muted hover:text-cyan">
                        {analyzing === c.name ? <Spinner size={12} /> : <FiRefreshCw size={12} />}
                      </button>
                      <button onClick={() => remove(c.id)}
                        className="w-7 h-7 rounded-lg hover:bg-white/10 flex items-center justify-center text-muted hover:text-red">
                        <FiTrash2 size={12} />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Analysis */}
          <div className="lg:col-span-2">
            {loading && (
              <div className="card flex flex-col items-center justify-center py-20">
                <div className="loading-dots flex justify-center mb-4"><span /><span /><span /></div>
                <p className="text-muted text-sm">Loading...</p>
              </div>
            )}

            {!loading && analysis && (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                {/* Header */}
                <div className="card">
                  <div className="flex items-center gap-4 mb-4">
                    {analysis.thumbnail ? (
                      /* eslint-disable-next-line @next/next/no-img-element */
                      <img src={analysis.thumbnail} alt={analysis.name}
                        className="w-14 h-14 rounded-2xl object-cover border border-white/10" />
                    ) : (
                      <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-cyan/20 to-magenta/20
                                    flex items-center justify-center text-2xl font-display text-white">
                        {analysis.name?.charAt(0)}
                      </div>
                    )}
                    <div>
                      <h2 className="text-xl font-bold text-white">{analysis.name}</h2>
                      <div className="text-muted text-sm">{analysis.platform}</div>
                    </div>
                    <AIBadge />
                    <button onClick={cloneChannel} disabled={cloning}
                      className="btn btn-cyan btn-sm gap-1.5 ml-auto">
                      {cloning ? <Spinner size={13} /> : <FiCopy size={13} />}
                      {cloning ? 'Building blueprint...' : 'Clone Channel'}
                    </button>
                  </div>
                  <div className="grid grid-cols-3 gap-3">
                    {[
                      { l: 'Est. Subscribers', v: analysis.estimatedSubscribers },
                      { l: 'Avg Views', v: analysis.avgViews },
                      { l: 'Engagement', v: analysis.engagementRate },
                    ].map(s => (
                      <div key={s.l} className="bg-surf2 rounded-xl p-3 text-center">
                        <div className="text-lg font-display text-cyan">{s.v || '—'}</div>
                        <div className="text-[10px] text-muted">{s.l}</div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Strategy */}
                  <div className="card">
                    <h4 className="font-bold text-white mb-3 text-sm">📋 Content Strategy</h4>
                    <p className="text-sm text-white/70 leading-relaxed">{analysis.contentStrategy}</p>
                    <div className="mt-3 flex flex-wrap gap-1.5">
                      {analysis.topContentTypes?.map((t: string, i: number) => (
                        <span key={i} className="badge-cyan text-[10px]">{t}</span>
                      ))}
                    </div>
                  </div>

                  {/* Keywords */}
                  <div className="card">
                    <h4 className="font-bold text-white mb-3 text-sm">🔑 Ranking Keywords</h4>
                    <div className="flex flex-wrap gap-1.5">
                      {analysis.rankingKeywords?.map((kw: string, i: number) => (
                        <span key={i} className="px-2 py-1 bg-surf2 border border-white/10
                                                 rounded-full text-xs text-white/70">{kw}</span>
                      ))}
                    </div>
                  </div>

                  {/* Strengths */}
                  <div className="card">
                    <h4 className="font-bold text-green mb-3 text-sm">✅ Strengths</h4>
                    <ul className="space-y-1.5">
                      {analysis.strengths?.map((s: string, i: number) => (
                        <li key={i} className="flex items-start gap-2 text-xs text-white/70">
                          <span className="text-green mt-0.5">→</span> {s}
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Opportunities */}
                  <div className="card">
                    <h4 className="font-bold text-cyan mb-3 text-sm">💡 Your Opportunities</h4>
                    <ul className="space-y-1.5">
                      {analysis.opportunities?.map((o: string, i: number) => (
                        <li key={i} className="flex items-start gap-2 text-xs text-white/70">
                          <span className="text-cyan mt-0.5">→</span> {o}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Recent videos with per-video analysis */}
                {analysis.recentVideos?.length > 0 && (
                  <div className="card">
                    <h4 className="font-bold text-white mb-3 text-sm">
                      🎬 Recent Videos ({analysis.recentVideos.length})
                    </h4>
                    <div className="space-y-2">
                      {analysis.recentVideos.map((v: any, i: number) => (
                        <div key={v.id || i}
                          className="flex items-center gap-3 p-2 rounded-xl hover:bg-white/5 transition-colors">
                          {v.thumbnail && (
                            /* eslint-disable-next-line @next/next/no-img-element */
                            <img src={v.thumbnail} alt=""
                              className="w-24 aspect-video object-cover rounded-lg flex-shrink-0" />
                          )}
                          <div className="flex-1 min-w-0">
                            <div className="text-sm text-white truncate">{v.title}</div>
                            <div className="text-xs text-muted">
                              {(v.views || 0).toLocaleString()} views{v.age ? ` · ${v.age}` : ''}
                            </div>
                          </div>
                          {v.url && (
                            <a href={v.url} target="_blank" rel="noopener noreferrer"
                              className="text-muted hover:text-white flex-shrink-0">
                              <FiExternalLink size={13} />
                            </a>
                          )}
                          {v.id && (
                            <button onClick={() => analyzeVideo(v.id)} disabled={seoLoading === v.id}
                              className="btn btn-ghost btn-sm gap-1 flex-shrink-0">
                              {seoLoading === v.id ? <Spinner size={11} /> : <FiZap size={11} />} Analyze
                            </button>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </motion.div>
            )}

            {/* ── Video SEO modal ── */}
            {videoSeo && (
              <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4"
                onClick={() => setVideoSeo(null)}>
                <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                  className="card max-w-lg w-full max-h-[85vh] overflow-y-auto border-cyan/20"
                  onClick={e => e.stopPropagation()}>
                  <div className="flex items-start justify-between gap-3 mb-4">
                    <div>
                      <div className="text-xs text-muted uppercase tracking-wider mb-1">Video Analysis</div>
                      <div className="text-sm font-bold text-white leading-tight">{videoSeo.video?.title}</div>
                      <div className="text-xs text-muted mt-1">
                        {(videoSeo.video?.views || 0).toLocaleString()} views · {videoSeo.video?.engagement}% engagement · {videoSeo.video?.tagCount} tags
                      </div>
                    </div>
                    <button onClick={() => setVideoSeo(null)} className="text-muted hover:text-white"><FiX size={18} /></button>
                  </div>
                  <div className="grid grid-cols-5 gap-2 mb-4">
                    {[
                      { l: 'Overall', v: videoSeo.seo?.score },
                      { l: 'Title', v: videoSeo.seo?.titleScore },
                      { l: 'Description', v: videoSeo.seo?.descriptionScore },
                      { l: 'Tags', v: videoSeo.seo?.tagsScore },
                      { l: 'Viral', v: videoSeo.seo?.viralScore },
                    ].map(s => (
                      <div key={s.l} className="bg-surf2 rounded-xl p-2 text-center">
                        <div className="font-display text-lg"
                          style={{ color: (s.v ?? 0) >= 70 ? '#00ff88' : (s.v ?? 0) >= 45 ? '#ffc740' : '#ff3366' }}>
                          {s.v ?? '—'}
                        </div>
                        <div className="text-[9px] text-muted">{s.l}</div>
                      </div>
                    ))}
                  </div>
                  {videoSeo.seo?.suggestions?.length > 0 && (
                    <div>
                      <div className="text-xs font-bold uppercase tracking-wider text-muted mb-2">How to beat this video</div>
                      <ul className="space-y-1.5">
                        {videoSeo.seo.suggestions.map((s: string, i: number) => (
                          <li key={i} className="flex items-start gap-2 text-xs text-white/70">
                            <span className="text-cyan mt-0.5">→</span> {s}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </motion.div>
              </div>
            )}

            {/* ── Clone Channel blueprint modal ── */}
            {blueprint && (
              <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4"
                onClick={() => setBlueprint(null)}>
                <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                  className="card max-w-2xl w-full max-h-[85vh] overflow-y-auto border-cyan/20"
                  onClick={e => e.stopPropagation()}>
                  <div className="flex items-start justify-between gap-3 mb-5">
                    <div>
                      <div className="text-xs text-cyan uppercase tracking-wider font-bold mb-1">✦ Channel Launch Blueprint</div>
                      <div className="text-sm text-muted">Inspired by {blueprint.sourceChannel}</div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button onClick={downloadBlueprintPDF} className="btn btn-cyan btn-sm gap-1.5">
                        <FiDownload size={12} /> Download PDF
                      </button>
                      <button onClick={() => setBlueprint(null)} className="text-muted hover:text-white"><FiX size={18} /></button>
                    </div>
                  </div>

                  <div className="space-y-5">
                    <div>
                      <div className="text-xs font-bold uppercase tracking-wider text-muted mb-2">Suggested Channel Names</div>
                      <div className="flex flex-wrap gap-2">
                        {(blueprint.suggestedNames || []).map((n: string, i: number) => (
                          <span key={i} className="badge-cyan text-sm px-3 py-1.5 font-bold">{n}</span>
                        ))}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs font-bold uppercase tracking-wider text-muted mb-2">Channel Description</div>
                      <div className="bg-surf2 rounded-xl p-3 text-sm text-white/80 leading-relaxed">
                        {blueprint.channelDescription}
                      </div>
                      {blueprint.tagline && (
                        <div className="text-xs text-cyan mt-2 italic">"{blueprint.tagline}"</div>
                      )}
                    </div>
                    <div>
                      <div className="text-xs font-bold uppercase tracking-wider text-muted mb-2">10 Launch Video Titles</div>
                      <ol className="space-y-1.5">
                        {(blueprint.titles || []).map((t: string, i: number) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-white/80">
                            <span className="text-cyan font-display text-xs mt-0.5 w-5">{i + 1}.</span> {t}
                          </li>
                        ))}
                      </ol>
                    </div>
                    {blueprint.contentPillars?.length > 0 && (
                      <div>
                        <div className="text-xs font-bold uppercase tracking-wider text-muted mb-2">Content Pillars</div>
                        <div className="flex flex-wrap gap-1.5">
                          {blueprint.contentPillars.map((p: string, i: number) => (
                            <span key={i} className="badge-cyan text-[10px]">{p}</span>
                          ))}
                        </div>
                      </div>
                    )}
                    {blueprint.firstWeekPlan && (
                      <div>
                        <div className="text-xs font-bold uppercase tracking-wider text-muted mb-2">First Week Plan</div>
                        <p className="text-sm text-white/70 leading-relaxed">{blueprint.firstWeekPlan}</p>
                      </div>
                    )}
                  </div>
                </motion.div>
              </div>
            )}

            {!loading && !analysis && (
              <EmptyState icon="👥" title="Select a competitor"
                description="Enter a channel name above to get AI-powered competitor analysis" />
            )}
          </div>
        </div>
      </div>
    </DashboardLayout>
  )
}

export default withAuth(CompetitorsPage)
