// pages/index.tsx
import React, { useEffect } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { motion } from 'framer-motion'
import { useAuth } from '../contexts/AuthContext'
import { FiArrowRight, FiCheck, FiZap, FiBarChart2, FiSearch, FiTrendingUp } from 'react-icons/fi'

const FEATURES = [
  { icon: '📊', title: 'Keyword Ranking %', desc: 'See exactly how likely each keyword is to rank your content in top results across all platforms.' },
  { icon: '✦', title: 'AI Writes Everything', desc: 'Title, description, tags, hook, and full script generated by SRankIQ AI in seconds.' },
  { icon: '🔬', title: 'SEO Scan Before Upload', desc: 'AI scans every field for optimization. Only green means go.' },
  { icon: '🌍', title: '7 Platforms', desc: 'YouTube, Instagram, TikTok, Facebook, X, LinkedIn, Pinterest — all in one dashboard.' },
  { icon: '📈', title: 'Real Analytics', desc: 'Live subscriber counts, views, engagement rates and growth tracking from your real accounts.' },
  { icon: '🎯', title: 'Competitor Intelligence', desc: 'Track competitors, analyze their strategy, and find gaps to exploit.' },
]

const PLANS = [
  { name: 'Starter', price: '0', period: 'forever', color: '#6060a0', features: ['3 platforms', '10 keyword searches/day', 'Basic AI generation', 'SEO scan (3/day)'], cta: 'Start Free' },
  { name: 'Basic', price: '5', period: 'month', color: '#b4ff00', features: ['5 platforms', '30 keyword searches/day', 'AI generation', 'SEO scan (1/day)', 'Analytics dashboard'], cta: 'Get Basic' },
  { name: 'Pro', price: '29', period: 'month', color: '#00f5ff', popular: true, features: ['All 7 platforms', 'Unlimited keyword research', 'Unlimited AI generation', 'Unlimited SEO scans', 'Competitor tracking', 'Advanced analytics'], cta: 'Start Pro' },
  { name: 'Agency', price: '99', period: 'month', color: '#ff0090', features: ['Everything in Pro', 'Team collaboration', 'White-label reports', 'Priority support', 'API access', 'Custom integrations'], cta: 'Go Agency' },
]

export default function LandingPage() {
  const { user, loading } = useAuth()
  const router = useRouter()

  useEffect(() => {
    if (!loading && user) router.replace('/dashboard')
  }, [user, loading, router])

  if (loading) return null

  return (
    <div className="min-h-screen bg-bg overflow-x-hidden">
      {/* Grid background */}
      <div className="fixed inset-0 grid-bg opacity-50 pointer-events-none" />

      {/* Orbs */}
      <div className="fixed top-0 left-1/4 w-96 h-96 rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(circle, rgba(0,245,255,0.08), transparent 70%)', filter: 'blur(40px)' }} />
      <div className="fixed bottom-1/4 right-1/4 w-64 h-64 rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(circle, rgba(255,0,144,0.08), transparent 70%)', filter: 'blur(40px)' }} />

      {/* NAV */}
      <nav className="fixed top-0 left-0 right-0 z-50 h-16 border-b border-white/5
                     bg-bg/80 backdrop-blur-xl flex items-center px-6 md:px-10">
        <div className="flex items-center gap-2 mr-auto">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/brand/logo-icon-cyan.png" alt="SRankIQ" width={36} height={36}
            style={{ width: 36, height: 36, objectFit: 'contain' }} />
          <span className="font-display text-xl tracking-wide">
            <span className="text-cyan">S</span>RankIQ
          </span>
        </div>
        <div className="flex items-center gap-3">
          <Link href="/login">
            <button className="btn btn-ghost btn-sm">Log In</button>
          </Link>
          <Link href="/signup">
            <button className="btn btn-cyan btn-sm">Start Free →</button>
          </Link>
        </div>
      </nav>

      {/* HERO */}
      <section className="min-h-screen flex items-center justify-center px-6 pt-16">
        <div className="text-center max-w-4xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full
                          bg-cyan/10 border border-cyan/20 text-xs font-bold text-cyan mb-6">
              ✦ Powered by SRankIQ AI
            </div>
          </motion.div>

          <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
            className="font-display text-6xl md:text-8xl leading-none tracking-wide mb-6">
            THE ONLY TOOL THAT{' '}
            <span className="grad-text">RANKS YOU</span>{' '}
            ON EVERY PLATFORM
          </motion.h1>

          <motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
            className="text-lg md:text-xl text-white/60 mb-10 max-w-2xl mx-auto leading-relaxed">
            7 platforms. AI-generated content. Real-time SEO scanning. Live keyword ranking percentages.
            Everything VidIQ should have built.
          </motion.p>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <Link href="/signup">
              <button className="btn btn-cyan btn-lg gap-2">
                Start Free — No Credit Card <FiArrowRight />
              </button>
            </Link>
            <Link href="/login">
              <button className="btn btn-ghost btn-lg">Log In to Dashboard</button>
            </Link>
          </motion.div>

          {/* Stats */}
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}
            className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-3xl mx-auto">
            {[
              { v: '47K+', l: 'Creators' },
              { v: '2.4M+', l: 'Content Optimized' },
              { v: '7', l: 'Platforms' },
              { v: '312%', l: 'Avg Growth' },
            ].map(s => (
              <div key={s.l} className="text-center">
                <div className="font-display text-3xl text-cyan neon-cyan">{s.v}</div>
                <div className="text-sm text-muted mt-1">{s.l}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="font-display text-5xl mb-4">
              EVERYTHING YOU NEED TO <span className="grad-text">DOMINATE</span>
            </h2>
            <p className="text-white/50 max-w-xl mx-auto">
              The most complete social media ranking and optimization platform ever built.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-px bg-white/5 rounded-xl overflow-hidden">
            {FEATURES.map((f, i) => (
              <motion.div key={f.title}
                initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }} viewport={{ once: true }}
                className="bg-bg p-8 hover:bg-surf transition-colors duration-200">
                <div className="text-3xl mb-4">{f.icon}</div>
                <h3 className="font-bold text-white mb-2">{f.title}</h3>
                <p className="text-sm text-muted leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section className="py-24 px-6 bg-surf/30">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="font-display text-5xl mb-4">SIMPLE, <span className="grad-text">HONEST</span> PRICING</h2>
            <p className="text-white/50">Start free. Scale as you grow.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
            {PLANS.map((plan, i) => (
              <motion.div key={plan.name}
                initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }} viewport={{ once: true }}
                className={`card relative ${plan.popular ? 'border-cyan/30 shadow-cyan' : ''}`}>
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 badge-cyan text-[10px]">
                    Most Popular
                  </div>
                )}
                <div className="text-sm font-bold uppercase tracking-wider mb-1" style={{ color: plan.color }}>
                  {plan.name}
                </div>
                <div className="flex items-end gap-1 mb-4">
                  <span className="font-display text-4xl" style={{ color: plan.color }}>${plan.price}</span>
                  <span className="text-muted text-sm mb-1">/{plan.period}</span>
                </div>
                <ul className="space-y-2 mb-6">
                  {plan.features.map(f => (
                    <li key={f} className="flex items-center gap-2 text-sm text-white/70">
                      <FiCheck size={12} style={{ color: plan.color }} className="flex-shrink-0" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Link href="/signup">
                  <button className={`btn w-full justify-center ${plan.popular ? 'btn-cyan' : 'btn-ghost'}`}>
                    {plan.cta}
                  </button>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 text-center">
        <motion.div initial={{ opacity: 0, scale: 0.95 }} whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="max-w-2xl mx-auto card border-cyan/20 shadow-cyan">
          <div className="font-display text-4xl mb-4">
            READY TO <span className="grad-text">RANK HIGHER?</span>
          </div>
          <p className="text-white/60 mb-8">Join 47,000+ creators already using SRankIQ to dominate their platforms.</p>
          <Link href="/signup">
            <button className="btn btn-cyan btn-lg">Get Started Free → No Credit Card</button>
          </Link>
        </motion.div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-white/5 py-10 px-6">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/brand/logo-icon-cyan.png" alt="SRankIQ" width={24} height={24}
              style={{ width: 24, height: 24, objectFit: 'contain' }} />
            <span className="font-display text-lg"><span className="text-cyan">S</span>RankIQ</span>
          </div>
          <p className="text-xs text-muted">© 2026 SRankIQ. Social Media Ranking Intelligence. All rights reserved.</p>
          <div className="flex gap-6 text-xs text-muted">
            <Link href="/privacy" className="hover:text-white">Privacy</Link>
            <Link href="/terms" className="hover:text-white">Terms</Link>
            <a href="mailto:support@srankiq.com" className="hover:text-white">Support</a>
          </div>
        </div>
      </footer>
    </div>
  )
}
